# Name of website
title: Filelife Official Website

# Short description of your site
description: The official FILELIFE Website

# Your name to show in the footer
author: Diego Tauchert

encoding: utf-8

social-network-links:
  email: "diego.tauchert@gmail.com"
  facebook: filelifeofficial
  github: diegotauchert
  twitter: diegotauchert
  rss: true
  reddit: diegotauchert
  linkedin: diegotauchert
  stackoverflow: "user:12755433/diego-tauchert"
  instagram: diegotauchert
  youtube: channel/UCEB0F2nYR3nADyJMqzWMh0g
  spotify: filelife
  telephone: +16175454437

share-links-active:
  twitter: true
  facebook: true
  linkedin: true

url-pretty: "filelife.co"
link-tags: true
excerpt_length: 50

title-separator: "-"
date_format: "%B %-d, %Y"
timezone: "America/Sao_Paulo"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5
kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
      readtime: false # add estimated reading time on all blog posts
  - scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

plugins:
  - jekyll-sitemap

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/
